server:
  port: 5000
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_app
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


