server:
  port: 5000
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_app
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "0gEKAXFRNhXbZZUa/Mz8/7sqhA4qF3yteUE4yIg4liX4yF3VuoWxh/GtgQ1RRE4VcDTqT0+D9DjL12Ixdec1tRuWshsGDyNS5uymtiPdihc="
