server:
  port: 5000
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_app
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "ziZgGScH9Jeq/H0VGuF/jFx0YYKZpjvYOL9ZbTpsP/DNefqqiYn6+ZZ6aOkn7IHqziZgGScH9Jeq/H0VGuF/jFx0YYKZpjvYOL9ZbTpsP/DNefqqiYn6+ZZ6aOkn7IHq"
